name: cashapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^25.1.35
  another_flutter_splash_screen: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins-bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: PoetsenOne
      fonts:
        - asset: fonts/PoetsenOne-Regular.ttf
